# Generated by Django 4.1.6 on 2023-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharing", "0002_order_message_bookavailable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressBarSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.IntegerField(default=0)),
                ("stage", models.CharField(default="Загрузка...", max_length=250)),
            ],
        ),
    ]
