# Generated by Django 4.1.6 on 2023-03-14 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sharing", "0005_alter_progressbarsession_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_close",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_open",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
