# Generated by Django 4.1.6 on 2023-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharing", "0011_message_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
